---
description: Putey Beta 2 Breadboard Computer
general:
  min_version: 0.1.5
  address_size: 16
  endian: little
  registers:
    - a
    - i
    - j
    - mar
    - sp
    - hl
    - h
    - l
operand_sets:
  8_bit_source:
    operand_values:
      a_register:
        type: register
        register: a
        bytecode:
          value: 0
          size: 3
      i_register:
        type: register
        register: i
        bytecode:
          value: 2
          size: 3
      j_register:
        type: register
        register: j
        bytecode:
          value: 3
          size: 3
      stack_pointer:
        type: indirect_register
        register: sp
        bytecode:
          value: 5
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
      immediate_value:
        type: numeric
        bytecode:
          value: 7
          size: 3
        argument:
          size: 8
          byte_align: true
  8_bit_destination:
    operand_values:
      a_register:
        type: register
        register: a
        bytecode:
          value: 0
          size: 3
      i_register:
        type: register
        register: i
        bytecode:
          value: 2
          size: 3
      j_register:
        type: register
        register: j
        bytecode:
          value: 3
          size: 3
      stack_pointer:
        type: indirect_register
        register: sp
        bytecode:
          value: 5
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
  16_bit_source:
    operand_values:
      hl_register:
        type: register
        register: hl
        bytecode:
          value: 0
          size: 3
      indirect_hl_register:
        type: indirect_register
        register: hl
        bytecode:
          value: 1
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      mar_register:
        type: register
        register: mar
        bytecode:
          value: 2
          size: 3
      indirect_mar_register:
        type: indirect_register
        register: mar
        bytecode:
          value: 3
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      stack_pointer:
        type: indirect_register
        register: sp
        bytecode:
          value: 5
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
      immediate_value:
        type: numeric
        bytecode:
          value: 7
          size: 3
        argument:
          size: 16
          byte_align: true
  16_bit_destination:
    operand_values:
      hl_register:
        type: register
        register: hl
        bytecode:
          value: 0
          size: 3
      indirect_hl_register:
        type: indirect_register
        register: hl
        bytecode:
          value: 1
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      mar_register:
        type: register
        register: mar
        bytecode:
          value: 2
          size: 3
      indirect_mar_register:
        type: indirect_register
        register: mar
        bytecode:
          value: 3
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      stack_pointer:
        type: indirect_register
        register: sp
        bytecode:
          value: 5
          size: 3
        offset:
          max: 255
          min: 0
          size: 8
          byte_align: true
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 6
          size: 3
        argument:
          size: 16
          byte_align: true
  address_source:
    operand_values:
      indirect_addr:
        type: indirect_numeric
        bytecode:
          value: 2
          size: 2
        argument:
          size: 16
          byte_align: true
      immediate_value:
        type: numeric
        bytecode:
          value: 3
          size: 2
        argument:
          size: 16
          byte_align: true
  incrementable_destination:
    operand_values:
      i_register:
        type: register
        register: i
        bytecode:
          value: 0
          size: 2
      j_register:
        type: register
        register: j
        bytecode:
          value: 1
          size: 2
      hl_register:
        type: register
        register: hl
        bytecode:
          value: 2
          size: 2
      mar_register:
        type: register
        register: mar
        bytecode:
          value: 3
          size: 2
  hl_subregisters:
    operand_values:
      subregister_h:
        type: register
        register: h
        bytecode:
          value: 1
          size: 1
      subregister_l:
        type: register
        register: l
        bytecode:
          value: 0
          size: 1
instructions:
  nop:
    byte_code:
      value: 0
      size: 8
  hlt:
    byte_code:
      value: 1
      size: 8
  # stack operations
  call:
    byte_code:
      value: 0
      size: 5
    operands:
      count: 1
      specific_operands:
        immediate_addr:
          list:
            addr:
              type: numeric
              bytecode:
                value: 3
                size: 3
              argument:
                size: 16
                byte_align: true
        direct_mar:
          list:
            mar:
              type: register
              register: mar
              bytecode:
                value: 4
                size: 3
  ret:
    byte_code:
      value: 6
      size: 8
  rsp:
    byte_code:
      value: 7
      size: 8
  push:
    byte_code:
      value: 1
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 8_bit_source
  push2:
    byte_code:
      value: 0b00010
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 16_bit_source
  pop:
    byte_code:
      value: 3
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 8_bit_destination
        disallowed_pairs:
          - [stack_pointer]
      specific_operands:
        no_operand:
          list:
            empty_op:
              type: empty
              bytecode:
                value: 7
                size: 3
  pop2:
    byte_code:
      value: 0b00100
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 16_bit_destination
        disallowed_pairs:
          - [stack_pointer]
      specific_operands:
        no_operand:
          list:
            empty_op:
              type: empty
              bytecode:
                value: 0b111
                size: 3
  # branching
  jmp:
    byte_code:
      value: 11
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - address_source
  jc:
    byte_code:
      value: 12
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - address_source
  jz:
    byte_code:
      value: 13
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - address_source
  jeq:
    byte_code:
      value: 2
      size: 3
    operands:
      count: 2
      operand_sets:
        reverse_argument_order: true
        list:
          - address_source
          - 8_bit_source
        disallowed_pairs:
          - [indirect_addr, a_register]
          - [immediate_value, a_register]
          - [indirect_addr, indirect_addr]
      specific_operands:
        iaddr_mar_offset:
          reverse_argument_order: true
          list:
            iaddr:
              type: indirect_numeric
              bytecode:
                value: 6
                size: 3
              argument:
                size: 16
                byte_align: true
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 6
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
  # data movement
  mov:
    byte_code:
      value: 2
      size: 2
    operands:
      count: 2
      operand_sets:
        list:
          - 8_bit_destination
          - 8_bit_source
        disallowed_pairs:
          - [a_register, a_register]
          - [i_register, i_register]
          - [j_register, j_register]
          - [stack_pointer, stack_pointer]
          - [stack_pointer, indirect_addr]
      specific_operands:
        a_mar:
          list:
            a:
              type: register
              register: a
              bytecode:
                value: 0
                size: 3
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 0
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
        i_mar:
          list:
            a:
              type: register
              register: i
              bytecode:
                value: 0b010
                size: 3
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 0b010
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
        j_mar:
          list:
            a:
              type: register
              register: j
              bytecode:
                value: 0b011
                size: 3
            mar:
              type: indirect_register
              register: mar
              bytecode:
                value: 0b011
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
        sp1_sp2:
          reverse_argument_order: true
          list:
            stack_pointer1:
              type: indirect_register
              register: sp
              bytecode:
                value: 5
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
                byte_align: true
            stack_pointer2:
              type: indirect_register
              register: sp
              bytecode:
                value: 5
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
                byte_align: true
        sp_iaddr:
          reverse_argument_order: true
          list:
            stack_pointer:
              type: indirect_register
              register: sp
              bytecode:
                value: 5
                size: 3
              offset:
                max: 255
                min: 0
                size: 8
                byte_align: true
            indirect_addr:
              type: indirect_numeric
              bytecode:
                value: 6
                size: 3
              argument:
                size: 16
                byte_align: true
        iaddr1_iaddr2:
          reverse_argument_order: true
          list:
            indirect_addr1:
              type: indirect_numeric
              bytecode:
                value: 6
                size: 3
              argument:
                size: 16
                byte_align: true
            indirect_addr2:
              type: indirect_numeric
              bytecode:
                value: 6
                size: 3
              argument:
                size: 16
                byte_align: true
    variants:
      - byte_code:
          value: 6
          size: 4
        operands:
          count: 2
          operand_sets:
            list:
              - hl_subregisters
              - 8_bit_source
            disallowed_pairs:
              - [subregister_l, indirect_hl_register]
              - [subregister_h, indirect_hl_register]
      - byte_code:
          value: 7
          size: 4
        operands:
          count: 2
          operand_sets:
            list:
              - 8_bit_destination
              - hl_subregisters
            disallowed_pairs:
              - [indirect_hl_register, subregister_l]
              - [indirect_hl_register, subregister_h]
          specific_operands:
            l_h:
              list:
                subregister_l:
                  type: register
                  register: l
                  bytecode:
                    value: 7
                    size: 3
              subregister_h:
                type: register
                register: h
                bytecode:
                  value: 1
                  size: 1
            h_l:
              list:
                subregister_h:
                  type: register
                  register: h
                  bytecode:
                    value: 7
                    size: 3
                subregister_l:
                  type: register
                  register: l
                  bytecode:
                    value: 0
                    size: 1
  swap:
    byte_code:
      value: 1020
      size: 10
      endian: big
    operands:
      count: 2
      operand_sets:
        list:
          - 8_bit_destination
          - 8_bit_destination
        disallowed_pairs:
          - [a_register, a_register]
          - [i_register, i_register]
          - [j_register, j_register]
          - [indirect_addr, indirect_addr]
  mov2:
    byte_code:
      value: 1021
      size: 10
      endian: big
    operands:
      count: 2
      operand_sets:
        list:
          - 16_bit_destination
          - 16_bit_source
        disallowed_pairs:
          - [indirect_hl_register, indirect_hl_register]
          - [indirect_hl_register, indirect_mar_register]
          - [indirect_hl_register, indirect_addr]
          - [mar_register, mar_register]
          - [indirect_mar_register, mar_register]
          - [indirect_mar_register, indirect_mar_register]
          - [indirect_mar_register, stack_pointer]
          - [indirect_mar_register, indirect_addr]
          - [stack_pointer, indirect_hl_register]
          - [stack_pointer, indirect_addr]
          - [indirect_addr, mar]
          - [indirect_addr, indirect_mar_register]
          - [indirect_addr, stack_pointer]
          - [indirect_addr, indirect_addr]
  # arithmetic operations
  add:
    byte_code:
      value: 23
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 8_bit_source
  sub:
    byte_code:
      value: 25
      size: 5
    operands:
      count: 1
      operand_sets:
        list:
          - 8_bit_source
  inc:
    byte_code:
      value: 54
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - incrementable_destination
  dec:
    byte_code:
      value: 55
      size: 6
    operands:
      count: 1
      operand_sets:
        list:
          - incrementable_destination
...
